yaml
name: Deploy to GitHub Pages
on:
 push:
 branches:
 - main # Trigger the workflow on push to the main branch
jobs:
 deploy:
 runs-on: ubuntu-latest
 steps:
 - name: Checkout code
 uses: actions/checkout@v2
 - name: Build site
 run: |
 mkdir -p build
 cp index.html build/index.html
 - name: Deploy to GitHub Pages
 uses: peaceiris/actions-gh-pages@v3
 with:
 github_token: ${{ secrets.GITHUB_TOKEN }}
 publish_dir: ./build

